name: iBeyblade
options:
  bundleIdPrefix: com.vidi
  deploymentTarget:
    iOS: "16.0"
configs:
  Debug: debug
  Release: release
packages:
  FirebaseSDK:
    url: https://github.com/firebase/firebase-ios-sdk
    from: 11.0.0
targets:
  iBeyblade:
    type: application
    platform: iOS
    deploymentTarget: "16.0"
    sources:
      - path: iBeyblade
    dependencies:
      - package: FirebaseSDK
        product: FirebaseAuth
      - package: FirebaseSDK
        product: FirebaseFirestore
    info:
      path: Generated/Info.plist
      properties:
        UILaunchScreen: {}
        UIRequiresFullScreen: true
        UIStatusBarHidden: true
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
        UISupportedInterfaceOrientations~ipad:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        CFBundleDisplayName: "iBeyblade"
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.vidi.iBeyblade
        SWIFT_VERSION: "5.0"
        TARGETED_DEVICE_FAMILY: "1,2"
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        CODE_SIGN_STYLE: Automatic
  iBeybladeUITests:
    type: bundle.ui-testing
    platform: iOS
    deploymentTarget: "16.0"
    sources:
      - path: iBeybladeUITests
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.vidi.iBeybladeUITests
        SWIFT_VERSION: "5.0"
        CODE_SIGN_STYLE: Automatic
        GENERATE_INFOPLIST_FILE: YES
    dependencies:
      - target: iBeyblade
schemes:
  iBeyblade:
    build:
      targets:
        iBeyblade: all
        iBeybladeUITests: [test]
    test:
      targets:
        - iBeybladeUITests
    run:
      config: Debug
